### ISSUE TITLE
!iam paging results issue

### ISSUE THREAD

**Issue by gobalopper** [Googer/Professor-Pine-old#14]
When paging between the results of the `!iam` command the previous pages data will sometimes be inserted before the correct text. See attached screenshots with an example from the Pittsburgh server. In this example the first two pages are fine but after the third it starts to break.

![page1](https://user-images.githubusercontent.com/10866784/43940375-8f2386be-9c2c-11e8-8b75-894b08cfa2db.png)
![page2](https://user-images.githubusercontent.com/10866784/43940376-8f431876-9c2c-11e8-9fed-490a7eb99919.png)
![page3](https://user-images.githubusercontent.com/10866784/43940377-8f5d7efa-9c2c-11e8-8be2-96333b7fdacb.png)
![page4](https://user-images.githubusercontent.com/10866784/43940378-8f72f5f0-9c2c-11e8-9965-d1a8846f0c03.png)
![page5](https://user-images.githubusercontent.com/10866784/43940414-c74c0afc-9c2c-11e8-8b47-be3718d5ab2f.png)
![page6](https://user-images.githubusercontent.com/10866784/43940381-8fab62e6-9c2c-11e8-8d7c-825a2ddc02c7.png)

**Comment by Googer** [comment]
I've too seen this before but it appears to be purely a Discord rendering issue.  You can prove it to yourself too - whenever you see some of an old page still rendering when switching to a new one, if you switch away from the-bot-lab channel to another one and switch back, the message is shown exactly correctly.

That said, I should change _how_ that message is rendered in the first place to make better use of Discord embed features.  Right now all of the role text is a single 'description' field instead of taking advantage of the fields that embed have (up to 25), which is how raid status messages (and Pine's help messages) are rendered.  That may or may not address this but at the very least will make the role paging message consistent with other similar messages that Pine generates.
